#spring.application.name=sistemaventas
spring:
  application:
    name: sistemaventas

  datasource:
    url: jdbc:postgresql://localhost:5432/sistemaventas
    jdbcUrl: url
    username: daniela
    password: 123456

  jpa:
    database-platform: 54
    hibernate:
      ddl-auto: update
    show-sql: true

  springdoc:
    api-docs:
      path: /api-docs
      enabled: true
    swagger-ui:
      path: /swagger-ui.html
      enabled: true

server:
  port: 5050

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
      preferIpAddress: true

